# Generated by Django 4.0.4 on 2022-10-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_alter_trip_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapi.tripstatus'),
            preserve_default=False,
        ),
    ]
