# Generated by Django 4.0.4 on 2022-10-30 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0006_user_kmprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='cost',
        ),
        migrations.AddField(
            model_name='trip',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='costs',
            field=models.ManyToManyField(related_name='costs', to='webapi.cost'),
        ),
    ]
