# Generated by Django 4.0.4 on 2022-10-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0008_ride_remove_trip_costs_delete_cost_ride_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kmprice',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
