# Generated by Django 4.0.4 on 2022-11-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0010_ride_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kmprice',
            field=models.DecimalField(decimal_places=1, default=0.7, max_digits=2),
        ),
    ]
